### ISSUE TITLE
Styling Options for q'n'eh Text and Images

### ISSUE THREAD

**Issue by crystalrubik** [cdig/q-n-eh#11]
Can we get an option for a border for images? It can be the same styling as what we have for the "framed" class in cd-module, but if it's tweakable, even better!

In Flash the code was `"round" : "true",`

We don't want it round now though.

Thanks!

**Comment by ivanreese** [comment]
What sort of options did you have in mind?

**Comment by ivanreese** [comment]
Also, why can't you use framed on an img? It should work fine.

**Comment by crystalrubik** [comment]
Well, right now we have:
```.framed {
    border: 3px solid #0063b3;
}```
in our CSS for the module. Which would be fine, but if there was an easy way for us to change it in case we ever make changes or want different colors, etc, that would be nice.

This is for Json stuff. 

```{
    "title" : "Drawing air into hydraulic lines happens more easily after shutdown, with the injector up high, above the power unit.",
    "image" : "question3.jpg",
    "answers": 
    {
    "a" : "True",
    "b" : "False"},

    "correct" : ["a"]
}```

**Comment by crystalrubik** [comment]
I don't know how to format the .json properly in that comment.... ^

**Comment by ivanreese** [comment]
Oh! I thought we were talking about module stuff. I didn't realize this was the q-n-eh repo. My mistake.

Sean and I will weigh our options and get back to you about this.

**Comment by crystalrubik** [comment]
Haha, sounds good.

**Comment by crystalrubik** [comment]
Ok, I wasn't thinking that it turns into html (idk why) so I now can style the borders by changing the css on the page for images... but now we're wondering how we would write json text that contains spans or something. So we can target just a phrase or a piece of the text.
 
Borders! Yay!
![q-n-eh](https://cloud.githubusercontent.com/assets/8481323/10207079/7bbc9c82-6787-11e5-8d6b-a16d4276cc1d.png)

Something like this? But obviously this doesn't work...
![example](https://cloud.githubusercontent.com/assets/8481323/10207151/e780e392-6787-11e5-81bd-ecee0ef76698.png)

**Comment by ivanreese** [comment]
You say "obviously this doesn't work"... but.. um... have you tried it?

**Comment by crystalrubik** [comment]
Haha, yes, we did for shits and giggles and it didn't... and we tried without the quotes as well.

**Comment by ivanreese** [comment]
Oh! Did you try this:

`"A <span class='blue-text'>sequence valve</span> uses single quotes?"`

**Comment by crystalrubik** [comment]
![span-test](https://cloud.githubusercontent.com/assets/8481323/10207742/9165bf56-678b-11e5-95df-403562e7c191.png)

**Comment by ivanreese** [comment]
Ah! Good to see that. We'll have to see what @theseanzo makes of it.

Just to be sure — you did run a bower-update, yes?

**Comment by crystalrubik** [comment]
I will do another one now just to be sure! But I believe I've updated it today.

**Comment by crystalrubik** [comment]
I guess I didn't... Haha. Now q'n'eh is broken. 
![error](https://cloud.githubusercontent.com/assets/8481323/10207880/836b2570-678c-11e5-9fa0-d93cf9866a98.png)

**Comment by theseanzo** [comment]
check the change in the read me

**Comment by iMcKelvie** [comment]
Cool! Is there documentation on how to style text, or will it be like in the example Crystal wrote? Or like Ivan's example of using single quotes inside of the text string?

**Comment by crystalrubik** [comment]
I added the line to the libs.js and I still get the exact same error. 
![added-line](https://cloud.githubusercontent.com/assets/8481323/10208352/041ffd96-6790-11e5-8bad-8d2d65db9117.png)
We even tried deleting the angular lines.
![deleted-lines](https://cloud.githubusercontent.com/assets/8481323/10208353/072b9f22-6790-11e5-9870-1f1a7f96e039.png)

**Comment by theseanzo** [comment]
It includes angular.js and angular-touch for you

**Comment by crystalrubik** [comment]
Yeah we seen that. So is there any other reason this error is still happening then?

**Comment by theseanzo** [comment]
Hmm. One second. Do a bower update in 5 minutes

**Comment by crystalrubik** [comment]
Text may now be styled in the questions and answers using span.
For example ```<span class='red-text'>sequence valve</span>```

Images may be styled by changing image css for the page the q'n'eh activity is on.
