### ISSUE TITLE
control over image size?

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/q-n-eh#12]
It would be fantastic to be able to have some control over the size of the image. Something similar to row="1/3", like we have for cd-row would be great! This would be especially nice when there is a question with a lot of text in the answer, but a relatively unimportant graphic, or vice versa, where the graphic is detailed and important, and the answers are very small.

**Comment by ivanreese** [comment]
* nod *

In the future, this will probably be rewritten to be a fair bit simple and expose more direct control over the HTML/Styling.

Keep the requests coming!

**Comment by ivanreese** [comment]
This is now possible using the `.q-n-eh-picture` class.
