### ISSUE TITLE
Adding respond option

### ISSUE THREAD

**Issue by AlexCDIG** [cdig/q-n-eh#2]
It will be nice to have "respond" field  which will be become visible when question will be answered correctly to put explanation comments on why it is right answer, and locate it under submit button.

**Comment by theseanzo** [comment]
Good suggestion. Maybe we could have a hover over the correct answer that explains it?

**Comment by ivanreese** [comment]
I'd strongly advise doing it the way Alex suggested. I've heard some pretty compelling arguments recently that there's a great deal more harm than good by making things happen on hover. And in this case, I think such explanation text would only make sense to use in cases where *everyone* should be expected to read it, no?

**Comment by ivanreese** [comment]
We'll be doing a clean-slate on activities next year.
