### ISSUE TITLE
Use Neutral Colours

### ISSUE THREAD

**Issue by ivanreese** [cdig/q-n-eh#5]
Note: Don't make the below changes until Robyn gives the okay.

According to Robyn, q-n-eh comes out-of-the-box with Trican's branding colours. This is a bug — it should either not specify colours at all (if possible), or if it needs to specify colours, it should use SCSS variables that do undefined checks (that is — if the variable is already specified, it uses the existing value).

**Comment by iMcKelvie** [comment]
Just checked with Carl - If we hit JUNE 30, and there haven't been requests for changes from Trican, we can consider that project closed. At that point it will be safe to go ahead with this change.

**Comment by ivanreese** [comment]
A: Knock Knock.

B: Who's there?

A: Trican updates after June 30th.

B: .... Stop coming to my house.

**Comment by crystalrubik** [comment]
Hey, when we change the button colors, can we also change the "good job" green to the green we now have in our key colors?
